// Generated by gencpp from file robot_sim/RobotPolicy.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_ROBOTPOLICY_H
#define ROBOT_SIM_MESSAGE_ROBOTPOLICY_H

#include <ros/service_traits.h>


#include <robot_sim/RobotPolicyRequest.h>
#include <robot_sim/RobotPolicyResponse.h>


namespace robot_sim
{

struct RobotPolicy
{

typedef RobotPolicyRequest Request;
typedef RobotPolicyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotPolicy
} // namespace robot_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_sim::RobotPolicy > {
  static const char* value()
  {
    return "3f378947ea88cc73ff6c322ead4c8836";
  }

  static const char* value(const ::robot_sim::RobotPolicy&) { return value(); }
};

template<>
struct DataType< ::robot_sim::RobotPolicy > {
  static const char* value()
  {
    return "robot_sim/RobotPolicy";
  }

  static const char* value(const ::robot_sim::RobotPolicy&) { return value(); }
};


// service_traits::MD5Sum< ::robot_sim::RobotPolicyRequest> should match 
// service_traits::MD5Sum< ::robot_sim::RobotPolicy > 
template<>
struct MD5Sum< ::robot_sim::RobotPolicyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::RobotPolicy >::value();
  }
  static const char* value(const ::robot_sim::RobotPolicyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::RobotPolicyRequest> should match 
// service_traits::DataType< ::robot_sim::RobotPolicy > 
template<>
struct DataType< ::robot_sim::RobotPolicyRequest>
{
  static const char* value()
  {
    return DataType< ::robot_sim::RobotPolicy >::value();
  }
  static const char* value(const ::robot_sim::RobotPolicyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_sim::RobotPolicyResponse> should match 
// service_traits::MD5Sum< ::robot_sim::RobotPolicy > 
template<>
struct MD5Sum< ::robot_sim::RobotPolicyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::RobotPolicy >::value();
  }
  static const char* value(const ::robot_sim::RobotPolicyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::RobotPolicyResponse> should match 
// service_traits::DataType< ::robot_sim::RobotPolicy > 
template<>
struct DataType< ::robot_sim::RobotPolicyResponse>
{
  static const char* value()
  {
    return DataType< ::robot_sim::RobotPolicy >::value();
  }
  static const char* value(const ::robot_sim::RobotPolicyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_ROBOTPOLICY_H
