// Generated by gencpp from file hand_analysis/GraspInfo.msg
// DO NOT EDIT!


#ifndef HAND_ANALYSIS_MESSAGE_GRASPINFO_H
#define HAND_ANALYSIS_MESSAGE_GRASPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_analysis
{
template <class ContainerAllocator>
struct GraspInfo_
{
  typedef GraspInfo_<ContainerAllocator> Type;

  GraspInfo_()
    : id(0)
    , emg()
    , glove()
    , glove_low_dim()
    , label(0)  {
    }
  GraspInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , emg(_alloc)
    , glove(_alloc)
    , glove_low_dim(_alloc)
    , label(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _emg_type;
  _emg_type emg;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _glove_type;
  _glove_type glove;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _glove_low_dim_type;
  _glove_low_dim_type glove_low_dim;

   typedef int32_t _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::hand_analysis::GraspInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_analysis::GraspInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GraspInfo_

typedef ::hand_analysis::GraspInfo_<std::allocator<void> > GraspInfo;

typedef boost::shared_ptr< ::hand_analysis::GraspInfo > GraspInfoPtr;
typedef boost::shared_ptr< ::hand_analysis::GraspInfo const> GraspInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_analysis::GraspInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_analysis::GraspInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_analysis

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hand_analysis': ['/home/minglun/project1_ws/src/project1/hand_analysis/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_analysis::GraspInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_analysis::GraspInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_analysis::GraspInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_analysis::GraspInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_analysis::GraspInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_analysis::GraspInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_analysis::GraspInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2f5dd8e97a79bb063f6e5cb0ae95755";
  }

  static const char* value(const ::hand_analysis::GraspInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2f5dd8e97a79bb0ULL;
  static const uint64_t static_value2 = 0x63f6e5cb0ae95755ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_analysis::GraspInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_analysis/GraspInfo";
  }

  static const char* value(const ::hand_analysis::GraspInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_analysis::GraspInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
float32[] emg\n\
float32[] glove\n\
float32[] glove_low_dim\n\
int32 label\n\
";
  }

  static const char* value(const ::hand_analysis::GraspInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_analysis::GraspInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.emg);
      stream.next(m.glove);
      stream.next(m.glove_low_dim);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_analysis::GraspInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_analysis::GraspInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "emg[]" << std::endl;
    for (size_t i = 0; i < v.emg.size(); ++i)
    {
      s << indent << "  emg[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.emg[i]);
    }
    s << indent << "glove[]" << std::endl;
    for (size_t i = 0; i < v.glove.size(); ++i)
    {
      s << indent << "  glove[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.glove[i]);
    }
    s << indent << "glove_low_dim[]" << std::endl;
    for (size_t i = 0; i < v.glove_low_dim.size(); ++i)
    {
      s << indent << "  glove_low_dim[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.glove_low_dim[i]);
    }
    s << indent << "label: ";
    Printer<int32_t>::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_ANALYSIS_MESSAGE_GRASPINFO_H
