(cl:defpackage robot_sim-srv
  (:use )
  (:export
   "ROBOTACTION"
   "<ROBOTACTION-REQUEST>"
   "ROBOTACTION-REQUEST"
   "<ROBOTACTION-RESPONSE>"
   "ROBOTACTION-RESPONSE"
   "ROBOTPOLICY"
   "<ROBOTPOLICY-REQUEST>"
   "ROBOTPOLICY-REQUEST"
   "<ROBOTPOLICY-RESPONSE>"
   "ROBOTPOLICY-RESPONSE"
  ))

