// Generated by gencpp from file robot_sim/RobotAction.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_ROBOTACTION_H
#define ROBOT_SIM_MESSAGE_ROBOTACTION_H

#include <ros/service_traits.h>


#include <robot_sim/RobotActionRequest.h>
#include <robot_sim/RobotActionResponse.h>


namespace robot_sim
{

struct RobotAction
{

typedef RobotActionRequest Request;
typedef RobotActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotAction
} // namespace robot_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_sim::RobotAction > {
  static const char* value()
  {
    return "deed0c4232f46b277ae3fb2459043f25";
  }

  static const char* value(const ::robot_sim::RobotAction&) { return value(); }
};

template<>
struct DataType< ::robot_sim::RobotAction > {
  static const char* value()
  {
    return "robot_sim/RobotAction";
  }

  static const char* value(const ::robot_sim::RobotAction&) { return value(); }
};


// service_traits::MD5Sum< ::robot_sim::RobotActionRequest> should match 
// service_traits::MD5Sum< ::robot_sim::RobotAction > 
template<>
struct MD5Sum< ::robot_sim::RobotActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::RobotAction >::value();
  }
  static const char* value(const ::robot_sim::RobotActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::RobotActionRequest> should match 
// service_traits::DataType< ::robot_sim::RobotAction > 
template<>
struct DataType< ::robot_sim::RobotActionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_sim::RobotAction >::value();
  }
  static const char* value(const ::robot_sim::RobotActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_sim::RobotActionResponse> should match 
// service_traits::MD5Sum< ::robot_sim::RobotAction > 
template<>
struct MD5Sum< ::robot_sim::RobotActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::RobotAction >::value();
  }
  static const char* value(const ::robot_sim::RobotActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::RobotActionResponse> should match 
// service_traits::DataType< ::robot_sim::RobotAction > 
template<>
struct DataType< ::robot_sim::RobotActionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_sim::RobotAction >::value();
  }
  static const char* value(const ::robot_sim::RobotActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_ROBOTACTION_H
