// Generated by gencpp from file robot_sim/RobotActionRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_ROBOTACTIONREQUEST_H
#define ROBOT_SIM_MESSAGE_ROBOTACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_sim
{
template <class ContainerAllocator>
struct RobotActionRequest_
{
  typedef RobotActionRequest_<ContainerAllocator> Type;

  RobotActionRequest_()
    : reset(false)
    , action()  {
    }
  RobotActionRequest_(const ContainerAllocator& _alloc)
    : reset(false)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::robot_sim::RobotActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_sim::RobotActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotActionRequest_

typedef ::robot_sim::RobotActionRequest_<std::allocator<void> > RobotActionRequest;

typedef boost::shared_ptr< ::robot_sim::RobotActionRequest > RobotActionRequestPtr;
typedef boost::shared_ptr< ::robot_sim::RobotActionRequest const> RobotActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_sim::RobotActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_sim::RobotActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_sim': ['/home/minglun/project2_ws/src/robot_sim/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::RobotActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::RobotActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::RobotActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79da883dcd5a0ceed7b1796e8e2c18ab";
  }

  static const char* value(const ::robot_sim::RobotActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79da883dcd5a0ceeULL;
  static const uint64_t static_value2 = 0xd7b1796e8e2c18abULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_sim/RobotActionRequest";
  }

  static const char* value(const ::robot_sim::RobotActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset\n\
float64[] action\n\
";
  }

  static const char* value(const ::robot_sim::RobotActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_sim::RobotActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_sim::RobotActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_ROBOTACTIONREQUEST_H
